# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2026-04-27 06:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import osf.models.base
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('addons_workflow', '0005_workflowactivation_is_dismissed'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTaskCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('task_id', models.CharField(db_index=True, max_length=64)),
                ('process_instance_id', models.CharField(max_length=64)),
                ('completed_at', osf.utils.fields.NonNaiveDateTimeField(default=django.utils.timezone.now)),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_task_completions', to='osf.AbstractNode')),
            ],
            options={
                'ordering': ('-completed_at',),
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.AlterUniqueTogether(
            name='workflowtaskcompletion',
            unique_together=set([('node', 'task_id')]),
        ),
    ]
