# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-06-10 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_s3', '0004_rename_deleted_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesettings',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
