# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-06-10 13:15
from __future__ import unicode_literals

from django.db import migrations
from addons.s3.utils import get_bucket_location_or_error
from addons.s3.settings import BUCKET_LOCATIONS


def populate_region_field(apps, schema_editor):
    NodeSettings = apps.get_model('addons_s3', 'NodeSettings')

    for node_setting in NodeSettings.objects.filter(folder_id__isnull=False):
        try:
            if node_setting.external_account:
                bucket_location = get_bucket_location_or_error(
                    node_setting.external_account.oauth_key,
                    node_setting.external_account.oauth_secret,
                    node_setting.folder_id
                )

                node_setting.region = bucket_location
                node_setting.save()

        except Exception as e:
            print(f'Failed to get region for bucket {node_setting.folder_id}: {e}')
            node_setting.region = 'us-east-1'  # aws default region
            node_setting.save()


def reverse_populate_region_field(apps, schema_editor):
    NodeSettings = apps.get_model('addons_s3', 'NodeSettings')
    NodeSettings.objects.update(region=None)

class Migration(migrations.Migration):

    dependencies = [
        ('addons_s3', '0005_nodesettings_region'),
    ]

    operations = [
        migrations.RunPython(
            populate_region_field,
            reverse_populate_region_field
        ),
    ]
