# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-03-14 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('addons_metadata', '0008_add_metadata_asset_pool'),
    ]

    operations = [
        migrations.RunSQL(
            [],
        ),
    ]
