# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-03-16 12:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.models.base
import logging

logger = logging.getLogger(__name__)


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0230_auto_20230314_0205'),
    ]

    operations = []

    logger.info('loa create.')
