# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-08-21 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0231_merge_20230713_1145'),
        ('osf', '0229_ensure_schema_and_reports'),
    ]

    operations = [
    ]
