# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-05-18 04:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0231_loa'),
    ]

    operations = []
