# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-10-03 05:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0233_add_conditional_required_to_registration_schema_block'),
        ('osf', '0232_auto_20230830_0425'),
    ]

    operations = [
    ]
