# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-05-18 04:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('osf', '0237_ensure_schema_and_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='loa',
            name='is_mfa',
            field=models.BooleanField(
                choices=[(False, 'Disabled'), (True, 'Enabled')], default=False, verbose_name='Display MFA link button'
            ),
        ),
        migrations.AlterField(
            model_name='loa',
            name='modifier',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, null=True
            ),
        ),
    ]
