# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-03-08 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0243_ensure_schema_mappings'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationschemablock',
            name='concealment_page_navigator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='get_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='get_retrieval_date',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='get_retrieval_title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='get_retrieval_version',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='multi_language',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='required_all_check',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='row_addition_caption',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='sentence',
            field=models.BooleanField(default=False),
        ),
    ]
