# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-11-10 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0257_merge_20251023_1304'),
        ('osf', '0254_registrationschemablock_display_template'),
    ]

    operations = [
    ]
