# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2026-02-02 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0261_mapcoregroup_mapcorenodegroup_mapcoreusergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapcorenodegroup',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterOrderWithRespectTo(
            name='mapcorenodegroup',
            order_with_respect_to='mapcore_group',
        ),
    ]
