# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2026-01-30 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0262_allow_empty_files_mapping'),
        ('osf', '0262_add_locked_column'),
    ]

    operations = [
    ]
