# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2026-02-23 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0262_auto_20260202_0643'),
        ('osf', '0263_merge_20260130_1152'),
    ]

    operations = [
    ]
