# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2026-03-25 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0264_merge_20260223_0712'),
        ('osf', '0264_merge_20260218_0749'),
    ]

    operations = [
    ]
