# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2026-04-17 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0265_merge_s3compatsigv4'),
        ('osf', '0267_split_name_fields'),
    ]

    operations = [
    ]
