# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2026-05-25 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0266_add_ui_to_registration_schema_block'),
        ('osf', '0266_merge_20260424_1200'),
        ('osf', '0268_merge_20260417_0525'),
    ]

    operations = [
    ]
