# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2026-06-15 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0265_merge_20260325_0957'),
        ('osf', '0269_merge_20260525_0425'),
    ]

    operations = [
    ]
