# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2026-06-16 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0269_merge_20260525_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionDefaultMaxQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('default_max_quota', models.IntegerField(default=100)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_max_quota', to='osf.Institution')),
            ],
            options={
                'db_table': 'osf_institution_default_max_quota',
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
    ]
