# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2026-06-22 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0270_merge_20260615_0523'),
        ('osf', '0270_remove_metadata_access_rights'),
    ]

    operations = [
    ]
