# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2026-07-13 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0266_r_2025_23_55789'),
        ('osf', '0271_merge_20260622_1735'),
    ]

    operations = [
    ]
