# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2026-09-22 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0272_merge_20260713_1135_'),
        ('osf', '0272_institutiondefaultmaxquota'),
    ]

    operations = [
    ]
